# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# If you want to automatically update fastlane if a new version is available:
# update_fastlane
# fastlane_version "1.98.0"

default_platform :ios

platform :ios do
  before_all do
    xcode_select "/Applications/Xcode.app"
    @output_folder = File.join(Dir.pwd, 'output')
  end

  desc "Runs all the tests"
  lane :test do
      scan(
        scheme: 'MVImageViewer',
        configuration: "Debug",
        code_coverage: true,
        clean: true,
        output_directory: @output_folder,
        output_types: "html, junit, json-compilation-database",
        use_clang_report_name: true
      )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
